# _config.yml

# Use a more specific theme, such as the one you've mentioned with additional customization.
theme: jekyll-theme-cayman
theme_config:
  # Add your customization here, e.g., navigation links, logo, etc.
  navigation:
    - title: "Home"
      url: "/"

